### ISSUE TITLE
chef/solr_query/query_transform missing in Chef 11

### ISSUE THREAD

**Issue by jsierles** [edelight/chef-solo-search#16]
## LoadError

cannot load such file -- chef/solr_query/query_transform
## Cookbook Trace:

  /chef/cookbooks/chef-solo-search/libraries/parser.rb:21:in `<top (required)>'

**Comment by rabidpraxis** [comment]
I was able to get this back working (in Chef 11.2) after pulling in some of the old solr code from 10.8:

https://github.com/rabidpraxis/chef-solo-search/commit/74ede9967e56f42da5f14aaf166559a266bc3a1e

Unfortunately, this requires you to install the 'treetop' gem before executing your run since it is no longer loaded with chef. Well, until this pull request comes in https://github.com/edelight/chef-solo-search/issues/17

**Comment by schisamo** [comment]
I opened https://github.com/edelight/chef-solo-search/pull/18 that covers ALL Chef 11 compat issues.

**Comment by marcellodesales** [comment]
I'm having this issue with Vagrant and Chef... Any way to get it working?

mdesales@Marcello-Work ~/dev/workboxes/cfp-workbox (master) $ vagrant provision
[default] Chef 11.8.2 Omnibus package is already installed.
[default] Running provisioner: chef_solo...
Generating chef JSON and uploading...
Running chef-solo...
stdin: is not a tty
[2013-12-25T04:17:20+00:00] INFO: Forking chef instance to converge...
[2013-12-25T04:17:20+00:00] INFO: **\* Chef 11.8.2 ***
[2013-12-25T04:17:20+00:00] INFO: Chef-client pid: 6024
[2013-12-25T04:17:20+00:00] INFO: Setting the run_list to ["recipe[apache2]", "recipe[vim]", "recipe[zsh]", "recipe[oh-my-zsh]", "recipe[users::ruby_shadow]", "recipe[users::sysadmins]", "recipe[users::sysadmin_sudo]"] from JSON
[2013-12-25T04:17:20+00:00] INFO: Run List is [recipe[apache2], recipe[vim], recipe[zsh], recipe[oh-my-zsh], recipe[users::ruby_shadow], recipe[users::sysadmins], recipe[users::sysadmin_sudo]]
[2013-12-25T04:17:20+00:00] INFO: Run List expands to [apache2, vim, zsh, oh-my-zsh, users::ruby_shadow, users::sysadmins, users::sysadmin_sudo]
[2013-12-25T04:17:20+00:00] INFO: Starting Chef Run for vagrant.vm
[2013-12-25T04:17:20+00:00] INFO: Running start handlers
[2013-12-25T04:17:20+00:00] INFO: Start handlers complete.
[2013-12-25T04:17:21+00:00] ERROR: Running exception handlers
[2013-12-25T04:17:21+00:00] ERROR: Exception handlers complete
[2013-12-25T04:17:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-12-25T04:17:21+00:00] ERROR: cannot load such file -- treetop

# 

# Recipe Compile Error in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/users/libraries/parser.rb

## LoadError

cannot load such file -- treetop

## Cookbook Trace:

  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/users/libraries/parser.rb:20:in `<top (required)>'

## Relevant File Content:

/tmp/vagrant-chef-1/chef-solo-1/cookbooks/users/libraries/parser.rb:

 13:  # Unless required by applicable law or agreed to in writing, software
 14:  # distributed under the License is distributed on an "AS IS" BASIS,
 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:  #
 19:
 20>> require 'treetop'
 21:  require 'chef/solr_query/query_transform'
 22:
 23:  # mock QueryTransform such that we can access the location of the lucene grammar
 24:  class Chef
 25:    class SolrQuery
 26:      class QueryTransform
 27:        def self.base_path
 28:          class_variable_get(:@@base_path)
 29:        end

[2013-12-25T04:17:20+00:00] INFO: Forking chef instance to converge...
[2013-12-25T04:17:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by tobami** [comment]
Which version are you using? master? 0.5.1?

**Comment by tobami** [comment]
Your `users/libraries/parser.rb` seems like an older version. Note how current master (and latest release) [do install it](https://github.com/edelight/chef-solo-search/blob/master/libraries/search.rb#L37)
